# Generated by Django 5.1.3 on 2024-11-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fine_tuning_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FineTuneModel',
            new_name='FineTunedModel',
        ),
    ]
